---
- name: Deploy Nginx in Docker Container with Host Path Mapping
  hosts: all
  become: yes

  tasks:
    - name: Ensure Nginx image is available (if not, it will be pulled)
      docker_image:
        name: nginx:latest
        source: pull

    - name: Create VCF Offline Bundle Server directory
      ansible.builtin.file:
        path: /vcf/
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create and start Nginx container with volume mapping
      community.docker.docker_container:
        name: VCF_Offline_Bundle_Server
        image: nginx:latest
        state: started
        restart_policy: always
        volumes:
          - "/vcf:/usr/share/nginx/html:rw"  # Map host directory to container's document root
        # Other optional configurations for Nginx container can be added here
        labels:
          # Add your custom Docker labels here
          deployment.environment: "{{ ansible_host }}_nginx"
          owner_team: it-support
          project.name: my_project
          description: "Nginx web server with content from host directory {{ inventory_hostname }}"
          com.example.version: 1.0.0
          com.example.description: VCF Offline Bundle Server
          traefik.enable: true
          traefik.http.routers.vcf.rule: Host(vcf.jameskilby.cloud)
          traefik.http.routers.vcf.entrypoints: websecure
          traefik.http.routers.vcf.tls: true
          traefik.http.routers.vcf.tls.certresolver: cloudflare
          traefik.http.services.vcf.loadbalancer.server.port: 80

