- name: Create vSwitch and port group on VMware host
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  vars:
    hostname: "your-esxi-host.local"
    username: "root"
    password: "your_esxi_password"
    validate_certs: false
    vswitch_name: "VLC-A"
    portgroup_name: "VLC-A-PG"
    mtu_size: 9000

  tasks:
    - name: Create vSwitch with no uplinks
      community.vmware.vmware_host_vss:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ hostname }}"
        switch_name: "{{ vswitch_name }}"
        mtu: "{{ mtu_size }}"
        nics: []   # No uplinks
        state: present

    - name: Create port group on the vSwitch
      community.vmware.vmware_portgroup:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        esxi_hostname: "{{ hostname }}"
        switch_name: "{{ vswitch_name }}"
        portgroup_name: "{{ portgroup_name }}"
        vlan_id: 0
        promiscuous_mode: true
        allow_forged_transmits: true
        allow_mac_changes: true
        state: present
