variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "datacenter" {}
variable "datastore" {}
variable "cluster" {}
variable "network" {}
variable "vm_folder" {}
variable "vm_name" {}
variable "iso_path" {}
