apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "300s"
      httpMethod: POST

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{container="${__span.tags.container}"} |= "${__trace.traceID}"'
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '-1h'
        queries:
          - name: 'Request Rate'
            query: 'rate(http_requests_total{service="${__span.tags["service.name"]}"}[1m])'
      nodeGraph:
        enabled: true